name: CD Publish Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.2.0
        with:
          java-version: 1.8
      - name: Publish with Gradle
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          GH_USER: ${{ secrets.GH_USER }}
          GH_PA_TOKEN: ${{ secrets.GH_PA_TOKEN }}
        run: ./gradlew cdPublish

  release:

    runs-on: ubuntu-latest
    needs: publish

    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
